name: dotnet
on:
  push:
    branches:
      - preview
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  
  build_nuget:
    needs: release
    name: Build NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Abp.Localization.Avalonia/Abp.Localization.Avalonia.csproj

      - name: Build
        run: dotnet build Abp.Localization.Avalonia/Abp.Localization.Avalonia.csproj --configuration Release --no-restore

      #  需要修改项目根目录下的 Directory.Build.props 中的Version跟package.json中的version一致
      - name: Update version
        run: |
          # Extract version from package.json
          VERSION=$(jq -r ".version" package.json)

          # Update Directory.Build.props with the extracted version
          sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|" Directory.Build.props

      - name: Commit changes
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --exit-code; then
            echo "No changes to commit"
          else
            # Add changes to git
            git add Directory.Build.props
          
            # Commit changes
            git commit -m "chore: update Directory.Build.props version"
          
            # Push changes to the repository
            git push origin HEAD:${{ github.ref }}
          fi


      - name: Publish NuGet package
        run: dotnet pack Abp.Localization.Avalonia/Abp.Localization.Avalonia.csproj --configuration Release --no-build -o out

      - name: Push to NuGet
        run: |
          dotnet nuget push out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols
